import React from'react';
import{Brush,Camera,ImageIcon,Layers,PenLine,Rotate3d,Search,WandSparkles}from'../../shared/icons/index.jsx';
import{resTypeName}from'../../appShared.jsx';
import{promotionFeatures,promotionOptionDefaults}from'./model/promotionFeatures.js';
import{WorkbenchCanvasToolbar,WorkbenchFeaturePanel,WorkbenchFeaturePopover,WorkbenchLeftPanel,WorkbenchRecentPanel,WorkbenchStudioControlPanel,WorkbenchStudioRecentStrip,WorkbenchVideoPanel}from'./components/index.jsx';

const featureList=[
  ['material','材质替换',Brush],
  ['replace_bg','场景融合',Layers],
  ['remove_bg','背景净化',WandSparkles],
  ['enhance','摄影增强',Camera],
  ['lineart','线稿图',PenLine],
  ['multiview','多角度视图',Rotate3d]
];

const promotionFeatureIconMap={
  promo_main_image:ImageIcon,
  promo_poster_image:WandSparkles,
  promo_detail_image:Search
};

export function buildWorkbenchPageSlots({
  mediaMode,
  op,
  ops,
  featureGroup,
  currentFeatureMode,
  currentFeatureLabel,
  featurePopover,
  closeFeaturePopover,
  activateFeatureGroup,
  selectPromotionFeature,
  selectBaseFeature,
  openFeaturePopover,
  setLeftDrawerOpen,
  setRightDrawerOpen,
  resourceKeyword,
  setResourceKeyword,
  resourceScope,
  setResourceScope,
  resourceItems,
  openWorkbenchResourceUpload,
  selectedResource,
  setSelectedResource,
  listImgSrc,
  removeOpts,
  setRemoveOpts,
  enhanceOpts,
  setEnhanceOpts,
  multiView,
  setMultiView,
  promotionOptions,
  setPromotionOptions,
  recentItems,
  recentKeyword,
  setRecentKeyword,
  refreshRecent,
  setRecentHoverId,
  recentHoverId,
  showRecentOriginal,
  moveRecentOriginal,
  hideRecentOriginal,
  openRecentTask,
  deleteRecentTask,
  recentTypeName,
  setMsg,
  goPage,
  showWorkbenchWatermark,
  workbenchWatermark,
  toggleWorkbenchWatermark,
  isPromotionSelected,
  custom,
  setCustom,
  reference,
  draggingRef,
  dragOver,
  dragLeave,
  dropUpload,
  chooseReference,
  imgSrc,
  clearReferenceImage,
  openResourceModal,
  studioLight,
  setStudioLight,
  resolution,
  setResolution,
  ratio,
  setRatio,
  gen,
  calcWorkbenchCost,
  me,
  storyboardDragging,
  setStoryboardDragging,
  dropStoryboard,
  chooseStoryboard,
  storyboards,
  removeStoryboard,
  videoPrompt,
  setVideoPrompt,
  videoParams,
  updateVideoParam
}){
  function updatePromotionOption(key,value){
    setPromotionOptions(prev=>({
      ...prev,
      [op]:{
        ...(promotionOptionDefaults[op]||{}),
        ...(prev[op]||{}),
        [key]:value
      }
    }));
  }

  const leftPanel=<WorkbenchLeftPanel
    mediaMode={mediaMode}
    op={op}
    ops={ops}
    promotionOptions={promotionOptions}
    updatePromotionOption={updatePromotionOption}
    resourceKeyword={resourceKeyword}
    setResourceKeyword={setResourceKeyword}
    resourceScope={resourceScope}
    setResourceScope={setResourceScope}
    resourceItems={resourceItems}
    openWorkbenchResourceUpload={openWorkbenchResourceUpload}
    selectedResource={selectedResource}
    setSelectedResource={setSelectedResource}
    listImgSrc={listImgSrc}
    resTypeName={resTypeName}
    removeOpts={removeOpts}
    setRemoveOpts={setRemoveOpts}
    enhanceOpts={enhanceOpts}
    setEnhanceOpts={setEnhanceOpts}
    multiView={multiView}
    setMultiView={setMultiView}
  />;

  return {
    featurePanel:<WorkbenchFeaturePanel
      currentFeatureMode={currentFeatureMode}
      currentFeatureLabel={currentFeatureLabel}
      setLeftDrawerOpen={setLeftDrawerOpen}
      featureGroup={featureGroup}
      mediaMode={mediaMode}
      openFeaturePopover={openFeaturePopover}
    >
      {leftPanel}
    </WorkbenchFeaturePanel>,
    featureDetailPopover:<WorkbenchFeaturePopover
      featurePopover={featurePopover}
      closeFeaturePopover={closeFeaturePopover}
      featureList={featureList}
      promotionFeatures={promotionFeatures}
      promotionFeatureIconMap={promotionFeatureIconMap}
      ops={ops}
      op={op}
      mediaMode={mediaMode}
      selectPromotionFeature={selectPromotionFeature}
      selectBaseFeature={selectBaseFeature}
      activateFeatureGroup={activateFeatureGroup}
    />,
    recentPanel:<WorkbenchRecentPanel
      mediaMode={mediaMode}
      recentItems={recentItems}
      recentKeyword={recentKeyword}
      setRecentKeyword={setRecentKeyword}
      refreshRecent={refreshRecent}
      setRightDrawerOpen={setRightDrawerOpen}
      setRecentHoverId={setRecentHoverId}
      recentHoverId={recentHoverId}
      showRecentOriginal={showRecentOriginal}
      moveRecentOriginal={moveRecentOriginal}
      hideRecentOriginal={hideRecentOriginal}
      openRecentTask={openRecentTask}
      deleteRecentTask={deleteRecentTask}
      recentTypeName={recentTypeName}
      listImgSrc={listImgSrc}
      setMsg={setMsg}
      goPage={goPage}
    />,
    studioCenterToolbar:<WorkbenchCanvasToolbar showWorkbenchWatermark={showWorkbenchWatermark} workbenchWatermark={workbenchWatermark} toggleWorkbenchWatermark={toggleWorkbenchWatermark}/>,
    studioControlPanel:<WorkbenchStudioControlPanel
      currentFeatureLabel={currentFeatureLabel}
      isPromotionSelected={isPromotionSelected}
      custom={custom}
      setCustom={setCustom}
      reference={reference}
      draggingRef={draggingRef}
      dragOver={dragOver}
      dragLeave={dragLeave}
      dropUpload={dropUpload}
      chooseReference={chooseReference}
      imgSrc={imgSrc}
      setMsg={setMsg}
      clearReferenceImage={clearReferenceImage}
      openResourceModal={openResourceModal}
      studioLight={studioLight}
      setStudioLight={setStudioLight}
      resolution={resolution}
      setResolution={setResolution}
      ratio={ratio}
      setRatio={setRatio}
      gen={gen}
      calcWorkbenchCost={calcWorkbenchCost}
      me={me}
    />,
    studioRecentStrip:<WorkbenchStudioRecentStrip
      recentItems={recentItems}
      recentTypeName={recentTypeName}
      setRecentHoverId={setRecentHoverId}
      showRecentOriginal={showRecentOriginal}
      moveRecentOriginal={moveRecentOriginal}
      hideRecentOriginal={hideRecentOriginal}
      openRecentTask={openRecentTask}
      listImgSrc={listImgSrc}
    />,
    videoCenterPanel:<WorkbenchVideoPanel
      storyboardDragging={storyboardDragging}
      setStoryboardDragging={setStoryboardDragging}
      dropStoryboard={dropStoryboard}
      chooseStoryboard={chooseStoryboard}
      storyboards={storyboards}
      removeStoryboard={removeStoryboard}
      videoPrompt={videoPrompt}
      setVideoPrompt={setVideoPrompt}
      videoParams={videoParams}
      updateVideoParam={updateVideoParam}
    />
  };
}
