import React,{useEffect,useState}from'react';
import{Bell,Building2,CheckCircle2,Download,Eye,Image as ImageIcon,Phone,Plus,Power,Search,SlidersHorizontal,Ticket,Trash2,UserRound,Video,WalletCards,X,XCircle}from'lucide-react';
import{API,token,req,reqForm,fmt,Badge,usePaged,Pagination,Table,Toolbar,roleName,audName,resTypeName,getStatusName,imageListUrl,fallbackToOriginalImage,openImageDownload}from'../../appShared.jsx';
import{featureName,getFeatureDisplayName,getTargetScopeDisplayName}from'../../config/uiText.js';

function Resources({setMsg}){
  const{query,setQuery,data,load}=usePaged('/api/admin/resources',{keyword:'',resourceType:'',status:''});
  const[f,setF]=useState({name:'',resourceType:'material',objectName:'',colorName:'',description:'',imageUrl:''}),[file,setFile]=useState(null),[preview,setPreview]=useState('');
  function chooseFile(e){const img=e.target.files?.[0];setFile(img||null);setPreview(img?URL.createObjectURL(img):'')}
  async function create(){try{const fd=new FormData();Object.entries(f).forEach(([k,v])=>fd.append(k,v??''));if(file)fd.append('image',file);await reqForm('/api/admin/resources',fd);setMsg('资源已创建');setF({name:'',resourceType:'material',objectName:'',colorName:'',description:'',imageUrl:''});setFile(null);setPreview('');load()}catch(e){setMsg(e.message)}}
  async function patch(id,status){try{await req('/api/admin/resources/'+id,{method:'PATCH',body:JSON.stringify({status})});load()}catch(e){setMsg(e.message)}}
  async function del(id){if(!confirm('删除系统资源？'))return;try{await req('/api/admin/resources/'+id,{method:'DELETE'});load()}catch(e){setMsg(e.message)}}
  return <div className="stack"><section className="panel"><h2><Plus/>新增系统资源</h2><div className="resourceCreate"><label className="uploadBox resourceUpload"><input type="file" accept="image/*" onChange={chooseFile}/>{preview?<img src={preview} loading="lazy" decoding="async"/>:<><ImageIcon size={36}/><b>上传资源图片</b></>}</label><div className="resourceForm"><div className="grid2"><input placeholder="资源名称" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><select value={f.resourceType} onChange={e=>setF({...f,resourceType:e.target.value})}>{Object.entries(resTypeName).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><input placeholder="物体/适用对象" value={f.objectName} onChange={e=>setF({...f,objectName:e.target.value})}/><input placeholder="颜色/色系" value={f.colorName} onChange={e=>setF({...f,colorName:e.target.value})}/><input placeholder="图片URL（可选）" value={f.imageUrl} onChange={e=>setF({...f,imageUrl:e.target.value})}/></div><textarea placeholder="资源说明" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/><button className="primary" onClick={create}>创建资源</button></div></div></section><section className="panel"><Toolbar onSearch={()=>setQuery(q=>({...q,page:1}))}><input placeholder="名称/物体/颜色" value={query.keyword} onChange={e=>setQuery({...query,keyword:e.target.value})}/><select value={query.resourceType} onChange={e=>setQuery({...query,resourceType:e.target.value})}><option value="">全部类型</option>{Object.entries(resTypeName).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select value={query.status} onChange={e=>setQuery({...query,status:e.target.value})}><option value="">全部状态</option><option value="ACTIVE">上架</option><option value="DISABLED">下架</option></select></Toolbar><div className="resourceGrid">{(data.items||[]).map(r=><div className="resourceCard" key={r.id}>{r.imageUrl?<img src={imageListUrl(r)} onError={e=>fallbackToOriginalImage(e,r)} loading="lazy" decoding="async"/>:<div className="resourcePh">{resTypeName[r.resourceType]}</div>}<b>{r.name}</b><span>{resTypeName[r.resourceType]} · {r.objectName||'-'} · {r.colorName||'-'}</span><p>{r.description}</p><div><button onClick={()=>patch(r.id,r.status==='ACTIVE'?'DISABLED':'ACTIVE')}>{r.status==='ACTIVE'?'下架':'上架'}</button><button className="danger" onClick={()=>del(r.id)}><Trash2 size={14}/>删除</button></div></div>)}</div><Pagination data={data} setQuery={setQuery}/></section></div>;
}

export default Resources;
